### ISSUE TITLE
arguments of gviewnl are misdesigned

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#222]
We have 

```
\begin{gviewnl}[keys]{name}{lang}{from}{to}
```

like `\gviewsig`, and have implemented independent deloading. But (like `\begin{gmodnl}{name}{lang}` we should just load the corresponding file `name.tex`. This also needs to be fixed in LaTeXML.

**Comment by cmaeder** [comment]
> like \begin{gmodnl}{name}{lang}

`gmodnl` is new to me (I only see i.e. `\begin{gstructure}{add}{cgroup}`)

**Comment by cmaeder** [comment]
Maybe you meant `mhmodnl`?

**Comment by kohlhase** [comment]
indeed I did

**Comment by kohlhase** [comment]
Hmmm, I am not sure that this is easy to implement, I tried, and there are problems. For instance, if we leave out the {from} and {to} arguments, we have to get them from the signature somehow, and that opens timing problems.

**Comment by kohlhase** [comment]
i think I know how to do this: 
when we expand
```
\begin{gviewnl}[keys]{name}{lang}
```
we input (like in ```\requiremodules{name}```. We update the code for ```\begin{view}``` to define token registers ```\views@<name>@from```, ```\views@<name>@to```, ```\views@<name>@frompath```, and ```\views@<name>@topath``` then we can use those to look up the values we need to proceed in ```gviewnl```. And then we can "activate" the view input.

**Comment by kohlhase** [comment]
OK, on (my currently local) ```gviewnl``` branch I have achieved the token registers. 
I think we can use ```\requiremodules``` directly.
