### ISSUE TITLE
Self-contained how-to document

### ISSUE THREAD

**Issue by dominique-unruh** [slatex/sTeX#232]
It would be great to have one self-contained walk-through example of how to create an OMDOC document from TeX source (and, e.g., view it in some OMDOC/MMT viewer). (I wanted to experiment with writing my papers in a semantic way but failed to get sTeX running.) SUch a walk-through would cover:

* **Installation and prerequisites.** Or links to instructions for all required components. Currently, it's difficult what is exactly needed. E.g., if I just try to use stex from CTAN, I lack required packages like pathsuris.sty. 

* **A minimal example.** Be it just a file which outputs $x^2$. It's not clear what one should include (e.g., I tried using modules.sty but that seems incompatible with LaTeXML, at least the version that came installed on my system).

* **The commands for converting to OMDoc and viewing.** I guess it's `latexmlc --profile stex --destination test.xml test`. But what then? Is that XML already the final result? Does it need postprocessing? Which of the MMT tools should I use to view it?

All of these infos are probably contained in various of the papers on the subject, but it is very hard to synthesize the right steps. (Also, some components may be outdated, etc.) Some of the problems above may actually bugs worth their own issues, but having a first supposedly running example would make it much easier to tell what should be reported and what is just a wrong setup on my side.

I'd be happy to support this by trying out the steps and giving feedback as a tech- and TeX-savvy outsider.

**Comment by kohlhase** [comment]
Indeed, it would be very good to have such a document. 

I am happy to hear that you are interested in using sTeX, and I would be happy to guide you through this, and then we could maybe based on that experience write such a document together. 

CAVEAT: the OMDoc generation is currently somewhat broken, but we will be working on this in the new year. But we can use the pdflatex workflow to get things going. 

Maybe the best thing would be do do a skype call (I am `mibein42`). Some time Friday would work for me.

**Comment by kohlhase** [comment]
A brief version of this should be in the top-level README.md
