### ISSUE TITLE
Make a self-contained documentation for the whole sTeX package

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/sTeX#242]
Please :)

**Comment by swalter62** [comment]
I second the motion. Also, why not start by fleshing out the section on metadata (§2.6)?

**Comment by kohlhase** [comment]
I have extended the overall sTeX documentation and while making a self-contained documentation (I understand this as a fully self-contained document) is infeasible, I have added hyper-references to all the package/class documentations in on the first page of https://github.com/sLaTeX/sTeX/raw/master/sty/stex/stex.pdf
Is this what you wanted?

**Comment by swalter62** [comment]
This is exactly what I wanted -- thanks a million! I look forward now to using sTeX and the LaTeXML plugin; thanks for your work, which I greatly appreciate!

**Comment by kohlhase** [comment]
Ah, great, but I am afraid, that the LaTeXML plugin needs quite a bit of work, still. But I am very confident that we are making progress in the next few months.

**Comment by swalter62** [comment]
This is good to know. I'm glad to serve as a beta-tester.

**Comment by swalter62** [comment]
Hmm. I see now what you mean about the LaTeXML plugin needing work. Infinite loop on the first test! Best of luck.

**Comment by kohlhase** [comment]
I am very hopeful, we are currently building up the testing infrastructure.
