### ISSUE TITLE
General Confusions (not sure which of these are actual issues)

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/sTeX#246]
Various confusions:

- Both `\symdef` and the `symboldec` environment elaborate (in LaTeXML) to a `<symbol>`-tag, but
- symbols declared via `symboldec` are not accessible in the latex document afterwards (no macro for them introduced). 
- This necessitates a duplication of declarations (once via `\symdef` just to get a corresponding latex macro) - but I'm entirely unsure what the point of `symboldec` then even is...?
- The `id`-parameter of `\symdef` does not seem to do anything. In the XML, the resulting symbol names are just `<modulename>.symbol<int>`.
- Similarly, the `name`-parameter of a `symboldef` does not seem to do anything.

The documentation is not very helpful with respect to what exactly is going on here. I would have expected that `\symdef` and `symboldec` behave identically, except for inline/environment behavior, with `id` and `name` having the same semantics in both cases. If so, `symboldec` needs some field for the notation.

**Comment by Jazzpirate** [comment]
Furthermore, the `role` tag of a `symboldec` is apparently not exported in the XML

**Comment by Jazzpirate** [comment]
`\symdef` does not generate any output in the pdf, which makes sense, since I'm guessing for presentational things `symboldec` is intended (except for the confusing behavior above).

`\symtype` however generates a rather ugly (and confusing) output. For example:
`\symtype[system=meta]{type}{\kind}` generates "Type(meta)type: kind". The `typedec`-environment however has a header as large as the one for `symboldec`, which makes it impossible to annotate a simple sentence in a `symboldec`-environment as a typing-declaration, or to introduce it separately without introducing weird pdf output

**Comment by Jazzpirate** [comment]
General LaTeXML errors:
- `Error:malformed:omdoc:symbol <omdoc:symbol> isn't allowed in <omdoc:theory>` - that can't possibly be right...?
- `Error:malformed:omdoc:theory <omdoc:theory> isn't allowed in <ltx:section>` - really? I'm not allowed to section my document?
- `Error:malformed:omdoc No namespace has been registered for prefix 'omdoc' (in code)
	at test.tex; line 42 col 0 - line 42 col 12
	Using 'http://example.com/namespace1' isntead`[sic] - interestingly, line 42 is just a `\section`... followed by `Warning:malformed:http://example.com/namespace1 No prefix has been registered for namespace 'http://example.com/namespace1' (in document)
	at test.tex; line 42 col 0 - line 42 col 12
	Using 'namespace2' instead`
- `Error:malformed:omdoc:notation <omdoc:notation> isn't allowed in <omdoc:theory>` - ???
- `Error:malformed:stex No namespace has been registered for prefix 'stex'`
- `Error:malformed:omdoc:prototype <omdoc:prototype> isn't allowed in <omdoc:notation>` (no idea what's even going on there...the `<prototype>` nodes only contain a malformed `<OMS>` with a namespace, but neither cd nor name...
- Consequently: `Error:malformed:om:OMS <om:OMS> isn't allowed in <omdoc:prototype>`
- `Error:malformed:omdoc:rendering <omdoc:rendering> isn't allowed in <omdoc:notation>`
- `Error:malformed:ltx:Math <ltx:Math> isn't allowed in <omdoc:rendering>`

There's dozens more of those `X isn't allowed in Y`-errors, so I'm skipping them now.

Unfortunately they very quickly add up, so now LaTeXML dies with "101 errors", which makes it difficult to continue testing:(

**Comment by Jazzpirate** [comment]
`\symtype`-XML-output is almost certainly broken:
`\symtype[system=meta]{type}{\LFkind}` is supposed to assign the type `\kind` to the symbol `type`, but both its `id` and `about` in the XML are `meta` and `#meta` respectively; the node contains to reference to `type` at all.

**Comment by Jazzpirate** [comment]
`\symdef` and `\vardef`behave exactly equally in the sense that the generated XML declares both as `<symbol>`s and references are in both cases `<OMS>`s instead of `<OMV>`s. This might be intended behavior, but it's counterintuitive.

**Comment by dginev** [comment]
While you're at it, could you confirm whether the `LaTeXML-Plugin-sTeX` repository passes `make test` successfully, just to be sure that all your reports are untested areas of sTeX? Thanks!

**Comment by Jazzpirate** [comment]
- Already the first test runs forever
- it unapologetically maxes out my CPU, freezing everything else
- it's not killable vie CTRL+c
- it's not killable via "kill PID" either

I now have two(!) unkillable perl processes running that make typing this here reaaaally difficult.

**Comment by dginev** [comment]
Excellent, please stop further testing until the test suite is back to functioning, otherwise you are diagnosing artefacts. Thanks for suffering (through)! You would like to do a `killall -9 perl` to cleanse you system.

**Comment by Jazzpirate** [comment]
Are you working on it (or plan to)? If so, let me know when I can resume testing. I might need your help with installing an updated plugin then, I vaguely remember that that was troublesome... :D

**Comment by dginev** [comment]
Not actively developing sTeX myself - no, as you can tell by the code stagnation. But I saw the notifications passing and quickly spotted that your tests are likely failing (and some of the schema errors reminded me the sTeX schema and model need to be regenerated to match the LaTeXML master).

**Comment by Jazzpirate** [comment]
I don't know what that means, but I guess @kohlhase and/or @tkw1536 do :D

**Comment by kohlhase** [comment]
`symboldec`, I have not used in years, so it should probably be considered deprecated.

**Comment by kohlhase** [comment]
the same holds for `\symtype`
