### ISSUE TITLE
sanitize smultiling and smglom bindings interface

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#250]
The interface (and implementation) of `smultiling` and `smglom` packages is not uniform. 
* we do not have `mhmodsig` (and use `modsig` instead)
* the implementation of `mhmodl` is not based on `modnl` as it should be
* `mhmdnl` has the file conventions of `smglom` baked in. We should really have (and use) `gmodsig` and `gmodnl` for `smglom` for that 
* the documentation is still too weak

**Comment by kohlhase** [comment]
attacking this problem in branch `sanitize-smglom`

**Comment by Jazzpirate** [comment]
`mhmodsig` is being used in smglom/IWGS/coding.tex, even though it doesn't exist. I'll change it to `modsig` locally. In the long term: should an `mhmodsig` exist or is that an error in the .tex-file?

**Comment by kohlhase** [comment]
both: in the long run I would like one, and currently (until then) it is an error.
