### ISSUE TITLE
Babel Bug

### ISSUE THREAD

**Issue by lambdaTotoro** [slatex/sTeX#260]
When I try to build certain sTeX documents (in this case `MiKoMH/IWGS/source/course/notes/notes.tex`) with `pdflatex` (or, for that matter, `xelatex`), I get the following complaint from the babel package about a re-definition. 
(The full output up to the first error can be found [here](https://pastebin.pl/view/fec6870f), should it be necessary)

```
[...]
(/usr/share/texmf-dist/tex/latex/base/latexsym.sty))
(/usr/share/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texmf-dist/tex/generic/babel/babel.def))
(/usr/share/texmf-dist/tex/latex/ntheorem/ntheorem.sty
Style `ntheorem', Version 1.33 <2011/08/15>
)) (/usr/share/texmf-dist/tex/latex/stex/structview/structview.sty
(/home/totoro/Development/KWARC/content/ext/sTeX/sty/mathhub/structview-mh.sty)
) (/usr/share/texmf-dist/tex/latex/stex/sproof/sproof.sty
(/usr/share/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texmf-dist/tex/generic/babel/babel.def
 
! LaTeX Error: Command \bbl@foreign@x already defined.
               Or name \end... illegal, see p.192 of the manual.
 
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                 
l.745   \endgroup}
                 
? 
```
This is consistent across two of my (independent) setups. You can kinda work around it by just continuing (i.e. press Enter on the prompt) but it would be nice to not have to babysit every pdflatex command for the forseeable future. `sTeX` is already on the newest version.

**Comment by kohlhase** [comment]
I remember seeing that error from time to time. It seemed to have been caused by a version update of babel.sty. 
A `git clean -xf` usually got rid of this. Unfortunately, I can never remember where to to this. I guess at MiKoMH/IWGS/

**Comment by kohlhase** [comment]
Oh, and have you seen https://github.com/latex3/babel/issues/69?

**Comment by lambdaTotoro** [comment]
Neither `git clean -xf` nor the recommended `fmtutil -user --all` have solved the problem, but I guess I'll make a bug report over there since this doesn't seem to be an sTeX-specific thing.
