### ISSUE TITLE
filestack: weird Heisenbug

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#270]
The Heisenbug on the AI notes is back. 
When I format `MathHub/MiKoMH/talks/source/kwarc/fragments/kwarc-ai.tex` I get errors coming from
`MathHub/MiKoMH/talks/source/kwarc/en/projectplan.tex` but when I format the latter directly, I do not. 
I thought this might have to do with nesting, and tried putting things into boxes, but this does not help either. 

This hinders me from compiling the AI course notes and the semester is coming.

**Comment by Jazzpirate** [comment]
Is this only on filestack or on master as well?

**Comment by kohlhase** [comment]
I am assuming both. But I have re-compiled the latex tools, and cannot run master any more (without effort) :grin:

**Comment by kohlhase** [comment]
It probably only needs an expert eye to see the error I cannot.

**Comment by Jazzpirate** [comment]
Yeah, but the expert eye will unfortunately be pretty blocked until sunday or possibly even monday, so if it's urgent I suggest trying master first :-/

**Comment by kohlhase** [comment]
Oh, I can always comment it out. 
So do not feel stressed.

**Comment by kohlhase** [comment]
I have some more data: The problems seem to be the `\TeX` and `\LaTeX` macros that are in used in there
```
\symdef{sTeXformat}{\text{sTeX}}
```
works, but 
```
\symdef{sTeXformat}{\text{\raisebox{-.5ex}S\kern-.5ex\TeX}}
```
does not.

**Comment by kohlhase** [comment]
```
\symdef{sTeXformat}{\text{\raisebox{-.5ex}S\kern-.5ex\protect\TeX}}
```
does not help either; but it is the \TeX and \LaTeX macros there that cause the problemsm. 
I am commenting this out for the moment, to make progress on the course.

**Comment by kohlhase** [comment]
Very weird, it has vanished again.
