### ISSUE TITLE
master: better error message for a semantic macro from an unimported module

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#271]
```
      \Trefiii[id-search]{iterative}{deepening}{search}
```
gives 
```
ERROR: Missing \endcsname inserted.

--- TeX said ---
<to be read again> 
                   \Moduleid-search 
l.10 ...i[id-search]{iterative}{deepening}{search}
                                                   is
--- HELP ---
```
when `id-search` is not imported. I would expect something like 
```
package modules Error: module id-search is not loaded, 
use \importmhmodule or \usemhmodule to do so
```
and that should be quite simple to do.

**Comment by Jazzpirate** [comment]
Fixed in 8e54453b24bde4b5517b44cef1f6731b8bc013ac

**Comment by kohlhase** [comment]
the new error message is good, but I get the following error-scape (and a missing blank in `computer-sciencenot loaded.`). 
Can't we be less verbose in these errors? The first one would really be enough. This seems like some fallback behavior ought to be done here. 
```

./matrix-complexity.tex:11: Package statements Error: Module computer-sciencenot loaded.

See the statements package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 ...iis[computer-science]{computer}{scientist}
                                                   an
./matrix-complexity.tex:11: Missing \endcsname inserted.
<to be read again> 
                   \Modulecomputer-science 
l.11 ...iis[computer-science]{computer}{scientist}
                                                   an
./matrix-complexity.tex:11: Missing \endcsname inserted.
<to be read again> 
                   \Modulecomputer-science 
l.11 ...iis[computer-science]{computer}{scientist}
                                                   an

./matrix-complexity.tex:11: Package modules Error: `\termref' with unidentified cd "\Modulecomputer-science uri".

See the modules package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.11 ...iis[computer-science]{computer}{scientist}
                                                   an

./matrix-complexity.tex:17: Package statements Error: \termrefwithout Module name, but not in a module. .
```

**Comment by Jazzpirate** [comment]
"Can't we be less verbose in these errors?" - we can't. That's just what TeX does when it does error recovery, which it does when you "skip" an error message. Only the first error message is mine, the latter are results of TeX just continuing despite the error.

**Comment by kohlhase** [comment]
can't we just define `\Modulecomputer-science`  to something bogus, or just skip the rest of the `\trefi`? After all, after an error all expectations on the result are off.

**Comment by Jazzpirate** [comment]
> can't we just define `\Modulecomputer-science` to something bogus,

I'd really rather not - no idea what might happen then if you actually try to import `computer-science`

> 
>  or just skip the rest of the `\trefi`? After all, after an error all expectations on the result are off.

Oh, it's just a `\trefi`... in that case probably, I'll check the macro implementation, but I'd rather you'd fix the error in your latex sources, tbh :D Also, it seems likely that if you forgot to include a module, then more errors of the same type will occur soon after, so just skipping the rest of \trefi will probably not give you *much* of an improvement...?

**Comment by kohlhase** [comment]
Of course I already _did_ fix the sources, but such errors often occur (for me), so good error messages are welcome (and not drowning in LaTeX's error recovery also helps.

**Comment by Jazzpirate** [comment]
ok, I'll look at `\termref` and try to skip the rest of the macro if an error occurs (if possible - I'll need to check where exactly the error even occurs. If it's too deeply nested, skipping becomes infeasible without rewriting \termref completely, which is on my agenda, but for sTeX2.0)

**Comment by Jazzpirate** [comment]
done in bfa4af712b5e69269ed626c8f699072fdaa47406 (not very nicely though :/ )
