### ISSUE TITLE
master feature: \ifinputref

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#274]
I would also like to have a flag `\ifinputref` that is set whenever a file is inputted via `\inputref` (and false otherwise).

**Comment by kohlhase** [comment]
@Jazzpirate you said this is easily done, and it would help me to have it soon.

**Comment by Jazzpirate** [comment]
done in b910317374dc10fda66e6898b0b19db7e5a6cae0

**Comment by kohlhase** [comment]
Thanks a lot, I have added some documentation.
