### ISSUE TITLE
smentry from smglom.dtx hard-codes the glossary entry module to foo

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#276]
I just re-noticed that `\begin{smentry}` creates a module with name `foo` for each of the glossary entries. 
I suspect that this will cause problems with the new sTeX which generates more links and checks more uniqueness.

**Comment by kohlhase** [comment]
We may have to generate 
```
\begin{smentry}{<lemma>}{<repos>}{<mod>}{<target>}
```
instead of the current
```
\begin{smentry}{\hypertarget{<target>}{<lemma>}}{<repos>}
```
and then assemble things accordingly in the definition of smentry. 
@jfschaefer you should probably go ahead and do that in any case. You should have the information around I believe.

**Comment by kohlhase** [comment]
Oh, and we have deprecated the `ext` key in `\importmhmodule`, so we should no longer generate
```
\usemhmodule[mhrepos=MiKoMH/IWGS,path=progintro/en/jupyterNotebooks,ext=tex]{jupyterNotebooks}
```
the `ext=tex` can just be dropped. Once you have done that, I can remove the key @dennis re-inserted.

**Comment by Jazzpirate** [comment]
This seems outdated
