### ISSUE TITLE
Indicate that a module was translated from another language

### ISSUE THREAD

**Issue by jfschaefer** [slatex/sTeX#283]
Currently, you can specify the creators and contributors of a module. E.g.
`\begin{mhmodnl}[creators=X]{M}{en}...`
If another person `Y` now translates `M` to another language, we currently can do
`\begin{mhmodnl}[creators=Y]{M}{de}...`
but it would probably make sense to indicate that it was translated:
`\begin{mhmodnl}[creators=Y,translatedfrom=en]{M}{de}...`

**Comment by kohlhase** [comment]
I had thought of this a while ago, and the question is what this means and how this is maintained. 
And whether this should be a directed link or we just want to state that two modules are translations of each other. 
The main problem I see is if `A` is transated from `B`, and then `A` or `B` further evolves without maintains the `translation` relation.

**Comment by Jazzpirate** [comment]
I think this is solved with the `sig=` attribute
