### ISSUE TITLE
Umlauts in German smglom files don't work

### ISSUE THREAD

**Issue by jfschaefer** [slatex/sTeX#284]
The pdf output still contains e.g. `k"onnen`.
An example file for reproduction is `smglom/sets/source/set.de.tex`.

**Comment by kohlhase** [comment]
Ah, I know, this is a casualty of the move to the new `standalone` setup. Previously, the `mmt make` setup prepended a `pre.de.tex` to the files. 
Now we need to include a `\usepackage[ngerman]{babel}` in the header. 
I will do so for SMGloM.

**Comment by kohlhase** [comment]
done.
