### ISSUE TITLE
Indented `solution` environment doesn't compile

### ISSUE THREAD

**Issue by jfschaefer** [slatex/sTeX#285]
The following example doesn't compile for me because of the indented `\begin{solution}...\end{solution}`:
```tex
\documentclass[solutions,notes,hints,pts,min,noauxreq,mh]{hwexam}
\begin{document}
\begin{problem}[title=Test,pts=25]
    ABC
    \begin{solution}
        DEF
    \end{solution}
\end{problem}
\end{document}
```
 I get the following error:
```
Processing 'solution' comment. Comment 'solution' writing to comment.cut.)
Runaway argument?
! File ended while scanning use of \next.
```

The following, however, compiles for me:
```tex
\documentclass[solutions,notes,hints,pts,min,noauxreq,mh]{hwexam}
\begin{document}
\begin{problem}[title=Test,pts=25]
ABC
\begin{solution}
    DEF
\end{solution}
\end{problem}
\end{document}
```

**Comment by kohlhase** [comment]
Indeed, the implementation of the solution environment uses the `comment` package, and that only works when the `\end{solution}` has no leading blanks. 
Michael

**Comment by kohlhase** [comment]
That is a "known  limitation".

**Comment by jfschaefer** [comment]
Oh, I see. Should I close the issue or leave it open with an *enhancement* label?

**Comment by kohlhase** [comment]
feel free to do either.
