### ISSUE TITLE
TODOs for sTeX3 release

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/sTeX#286]
- [x] Mathematical structures
- [x] Mod Types & Instances
- [x] Sequence variables/declarations: Might be tricky until deadline, requires design. On the other hand: Might be useful to have syntax for that in stex.sty to minimize "breaking" changes in future updates
- [x] sproofs needs a redo => systematize customizations etc
- [ ] Go over the whole code (especially the extensions) and clean up / document. There's likely an unreasonable amount of migration/legacy stuff that should be gotten rid of (e.g. former customization in problem and new customization via sproblem)
- [ ] Maybe: Start refactoring/reimplementing/translating the SMGloM properly, in new repositories, with type annotations etc, documentation, with a somewhat reasonable repo/namespace/directory structure. We don't need everything, but we should at least start so we have something to point to as a properly idiomatic reference library that demonstrates all the new shiny things, without them being buried in ""legacy""-modules. We can still point to the existing smglom as a repo of content-we-already-have-and-can-use-except-for-potential-deprecation-and/or-migration.
- [x] MMT Structures
- [x] Set/change default notations 
- ~[ ] (globally? Might get tricky)~ unrealistic, probably
- [x] Variables
- [x] Redesign the notation and symbol/variable-invokation code to be compatible with this kind of arbitrary-text-annotation-syntax: 
   ```\vardef*[varn,varm]{Let $\varnot[varn]{n},\varnot[varm]{m}$, be \symtype[varn,varm]\NaturalNumbers{natural numbers}} such that \premise{...}```
- [x] Premises etc in definitions / statements (? => Allow MMT to assemble individually annotated components into a single term)
- [x] reference targets for symbols
- [x] get extensions/problems.sty and hwexam.cls/sty to run with MiKoCourses. Currently,  the exams (e.g. `MiKoCourses/AI/source/SS20/orig.exam.en.tex` do not even run through that should be fixed). 
- [x] We should also have an environment `{sproblem}`, that behaves like `{sexample}` in that its presentation  can be specialized. 
- [x] multilinguality/babel stuff
- [x] split up mikoslides / omdoc a.k.a. document-structure into generic and miko-specific stuff
- [x] views or something like it (e.g. realizes) ( = interpretmodule )
- [x] get rid of all the compatibility (from the sTeX sources) and the package `stex-compatibility` <- this is not an sTeX-TODO, that's more like an smglom-TODO - nothing in compatibility "should" be used at all, but the smglom *might* in some instances, and MiKoMH probably does *a lot*.
- [x] allow subgroups for repositories
- [x] Module/symbol deprecation
- [x] ~maybe~ redesign smsmode (catcode switching causes problems - use \read instead and iterate over token list?)
- [x] associative notations -> have `[args=ai]{foo}{[#1]_{#2}}{##1 + ##2}` instead, expand to `{[\stex_assoc:nn{#1}{##1 + ##2}]_{#2}}`
- [x] `type=symdoc` for sparagraph (MMT)
- [x] `assoc=` key for symdef (how to "resolve" associative arguments): `bin` (associative binary), `binl` (left-associative) `binr` (right-associative), `pre` (as in nested quantifiers), `conj` (conjunctive, as in a=b=c => a=c /\ b = c, or a,b=/=c => a=/=c /\ b=/=c), `pwconj` (pair-wise conjunctive, as in a=/=b=/=c), ...
- [x] add some kind of "link" or "popup" for `\symname` and `\comp` whenever the definition is in the same document. After all, that is the only direct benefit we provide for all that markup. 
- [ ] fully semantify and split up the documentation as a showcase repo in gl.mathub.info/sTeX ?

**Comment by kohlhase** [comment]
ad. sTeX-compatibility: MiKoMH does not use any more compatibility than smglom.

**Comment by Jazzpirate** [comment]
> ad. sTeX-compatibility: MiKoMH does not use any more compatibility than smglom and (like SMLoM) does not intend to use any. This is why I propose to get rid of `stex-compatibility.sty` completely and not release it at all. That also takes care of the Maybe comment after that.

Even better - but I don't see how it solves the latter point - that's mostly about "how do we organize the smglom better", splitting up big modules into small ones, having separate files for declarations+documentation, "formal" definitions (in particular where multiple definitions exist), examples, theorems etc, maybe merging some fragments from MiKoMH in there to have some less formal sparagraphs in there too... all the things that people should be able to reuse, or might be relevant for guided tours that are not more general than specific MiKo-courses etc

**Comment by Jazzpirate** [comment]
> you are right, it solves the compatibility layer problem, not the "showcase" problem. About the showcase, I am all against having two copies of smglom (one showcase and one "real"). If you want to showcase things, use HelloWorld.

It's not (just) about showcasing things - the "showcase" library is what the smglom should (in due time) *be*, after a thorough refactoring ;)
The main thing is that refactoring the whole smglom will be very time consuming, so I think it's a good idea to start early, plan a somewhat decent repository/directory/namespace structure that we want to use and start refactoring a small fragment (e.g. mv and all-the-things-in-sets-that-aren't-actually-about-sets). Then the result can serve as both a showcase *and* as something that e.g. we can have students fill up with the content in the (current) smglom

**Comment by kohlhase** [comment]
yeah, then I agree fully. 

But the refactoring is dangerous, since it can break anything that references the SMGloM. So indeed, we should start this early, while all the content in danger is mine.

**Comment by Jazzpirate** [comment]
Yes - which is also why I would prefer a separate git group/repo rather than branches that would have to be switched etc.

Then the "old" smglom can just continue to exist, you can keep using them, other people *can* use them (being aware that it's "deprecated"), and the new one is what we encourage people to *actually* use and extend :)

**Comment by Jazzpirate** [comment]
On that note: At *some* point we're going to need a "deprecate and redirect" mechanism of some sort, for change management. But I would defer that to some later point

**Comment by Jazzpirate** [comment]
\definiendum, \definame, \symname brauchen root=,post=,pre=
\synonym = \symref + root=,pre=,post=

\symdecl\symdef\notation switch argument order

\vardef*[varn,varm]{Let $\varnot[varn]{n},\varnot[varm]{m}$, be \symtype[varn,varm]\NaturalNumbers{natural numbers}} such that \premise{...}

**Comment by kohlhase** [comment]
Can we close this, after all, the release has happened.

**Comment by kohlhase** [comment]
I spun out the remaining three todos, closing
