### ISSUE TITLE
port FAUexam.sty

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#287]
We have to port `MathHub/MiKoCourses/meta-inf/lib/FAUexam.sty` which makes the FAU variant of the `{testheading}` environment for FAU. I have already given {testheading} another `tools=` key, but the key needs to be used in FAUexam.sty correctly. 

```
\libusepackage[de,en,detitle]{FAUexam}
```
will make the German and English explanatory text and sets the Title in German

You can use `MathHub/MiKoCourses/IGWS/source/WS2122/exam.tex` as a test file. 

While there, this uses `\ifsolutions`, which seems to have disappeared.

**Comment by Jazzpirate** [comment]
Fixed
