### ISSUE TITLE
babel treatment with lang=

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#290]
- [x] I have a couple of occurrences where I want multiple languages, does `lang={de,en}` work? 

- [x] In the turkish files, we needed 
```
\usepackage[turkish,shorthands=:!]{babel}% restricted shorthands, otherwise we have problems with keyval, which we need
```
to make LaTeX happy, is this information used in sTeX? 

- [ ] dito for chinese: There I currently have 
```
\usepackage{fontspec}
\setmainfont[AutoFakeBold=4]{FandolFang}
\XeTeXlinebreaklocale "zh"
\XeTeXlinebreakskip = 0pt plus 1pt minus 0.1pt
```
Is that possible to put into the language handling?

**Comment by Jazzpirate** [comment]
> 
>     * [ ]  dito for chinese: There I currently have
> 
I - for now - can take no responsibility for chinese, for the simple reason that I have not experimented with xetex at all. Also, RusTeX won't be able to handle xetex commands, like the above three...

**Comment by kohlhase** [comment]
> I - for now - can take no responsibility for chinese, for the simple reason that I have not experimented with xetex at all. 

Unfortunately, I do not have real experience with chinese either, but I maintain, the `lang=` mechanism should be sufficient to handle the chinese stuff gracefully (at least at the PDF side). 

> Also, RusTeX won't be able to handle xetex commands, like the above three...

all the more reason not to have them explicitly in the source code.

**Comment by kohlhase** [comment]
Dennis complains about setting an arbitrary sytstem font in an sTeX package; and I agree, even though I maintain the details  of handling chinese in TeX should be hidden from the user and not be part of the math archives. 

The current xetex/FandolFang based solution is the recommendation of about 7 years ago, maybe something better has emerged, e.g. one of the solutions described in https://www.overleaf.com/learn/latex/Chinese works better by now.

**Comment by Jazzpirate** [comment]
moved into a separate issue
