### ISSUE TITLE
notesslides.cls topsect still broken 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#291]
In the AI notes I have 
```
\documentclass[class=book,notes]{notesslides}  
```
and that does not give me parts; this behaves as if there were a `topsect=chapter` in there.

**Comment by Jazzpirate** [comment]
it works for me - but until I pulled MiKoMH/AI, I had an explicit `topsect=chapter` in there for some reason - with a fresh pull (i.e. without topsect) and after building twice, I have the parts in there as intended...?

**Comment by kohlhase** [comment]
will try again and report.

**Comment by kohlhase** [comment]
Indeed, sorry for the uproar,.
