### ISSUE TITLE
beamerarticle or notesslides itemize does not play well with sparagraph

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#295]
There is a curious (and very annoying) interaction between the `itemize` env from `beamerarticle.sty` or `notesslides.sty`and the `sfragment` env from `sTeX`. Note that this only seems to apply to `notes` mode.  

The spacing is off and the placement of the item mark is offer. E.g. 
* in `MiKoMH/IWGS/source/databases/mod/redundancy.en.tex`: 
<img width="727" alt="Screenshot 2022-05-06 at 08 11 57" src="https://user-images.githubusercontent.com/4037538/167077082-8b4f923a-87df-41ce-8ee8-bc66757a279a.png">
* in `MiKoMH/IWGS/source/databases/mod/python-sqlite.en.tex` we see 
<img width="834" alt="Screenshot 2022-05-06 at 08 18 19" src="https://user-images.githubusercontent.com/4037538/167077612-e503657d-77d4-4af3-8c9f-102aee3200db.png">
I have no idea where the item mark in the title even comes from, it does not seem to be in the source. 
* conversely in `MiKoMH/IWGS/source/databases/mod/sqlite-create.en.tex` the item mark is completely missing. 
<img width="758" alt="Screenshot 2022-05-06 at 08 20 23" src="https://user-images.githubusercontent.com/4037538/167077870-62ee798e-7824-4383-8de3-51f805245241.png">
but there is a spurious one in the title of the next slide, maybe that's where it went. 
<img width="852" alt="Screenshot 2022-05-06 at 08 21 40" src="https://user-images.githubusercontent.com/4037538/167078004-591a3a6e-bb86-4da2-a219-d6fea78b79de.png">
* in `MiKoMH/IWGS/source/databases/mod/database.en.tex` item mark bunch up: 
<img width="716" alt="Screenshot 2022-05-06 at 08 22 31" src="https://user-images.githubusercontent.com/4037538/167078161-e4fc46a6-775c-4b24-8c07-35895d4dc585.png">

This covers most of the cases I have seen, this probably has a common source, so I will not try to collect more examples.

**Comment by kohlhase** [comment]
BTW, this **not** a regression this bug has been present for years (at least).

**Comment by kohlhase** [comment]
It would be great, if we were able to fix this.

**Comment by Jazzpirate** [comment]
notesslides defines its own `frame`-environment, which redefines the `itemize`-environment. All of this seems somewhat hacky to me and I'm not entirely sure what the *exact* intentions behind all of those are. That should be rethought from the ground up, probably

**Comment by kohlhase** [comment]
I agree with that. That is why I am collecting the evidence.

**Comment by kohlhase** [comment]
> notesslides defines its own `frame`-environment, which redefines the `itemize`-environment.

This is one of the first things I did for sTeX, and I think that the beamerarticle functionality may have improved over time, so that we do not have to do that any more.

**Comment by kohlhase** [comment]
I would really like to leave the implementation of frames in notes to Till Tantau and his friends

**Comment by kohlhase** [comment]
Interestingly, in `MathHub/MiKoMH/AI/source/probabilistic-reasoning/mod/uncert-sensors.en.tex`, both the PDF
<img width="440" alt="Screenshot 2022-05-06 at 13 08 36" src="https://user-images.githubusercontent.com/4037538/167120551-6a538d7f-e352-46f4-8c87-b4235136fddb.png">
and the generate HTML
<img width="700" alt="Screenshot 2022-05-06 at 13 06 56" src="https://user-images.githubusercontent.com/4037538/167120573-4c21666f-036f-4293-822c-d419a3cde243.png">
have item label problems.

**Comment by kohlhase** [comment]
this seems to have been finally fixed thanks to @Jazzpirate
