### ISSUE TITLE
marking up defining occurrences of symbols (with notations but without verbalizations)

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#307]
We can currently mark up the defining occurrence of the verbalization of a symbol with `\definiendum` or `\definame`. That takes care of all symbols that have verbalizations. But there are symbols (e.g. `\UnionCollection` from `smglom/sets/source/union.en.tex`) that do not have verbalizations. For those we can only use the `\begin{sdefinition}[for=UnionCollection}` mechanism, which is a bit coarse (it only says "what definition", not "where in that definition", which could inform presentational semantic services). 

I am not sure that the best way of doing this is, but I could imagine that a `\symdef{foo}` and `\notation{foo}` defines a new macro `\foo*`, which expands exactly like `\foo`, only that it marks the occurrence as defining. 

We currently have (and use) the `\defeq` and `\fundefeq` symbols that "do the right thing", but not at the sTeX level that I am calling for here. We could also use the `\definiendum` function differently in math mode. Then `\foo*` from above would be an abbreviation of `\definiendum{foo}\foo`.

**Comment by Jazzpirate** [comment]
Duplication of #326
