### ISSUE TITLE
something bleeds spaces

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#310]
Something (probably `\usemodule`) bleeds spaces, e.g. in `MathHub/MiKoMH/IWGS/source/booksapp/snip/books-app.en.tex`, which has
```
\begin{sparagraph}
  \usemodule[MiKoMH/GenCS]{www/mod?webapps}
  \usemodule{webapps/mod?bottle-stpl}
  \usemodule[MiKoMH/GenCS]{www/mod?serverside-scripting}
```
and yields
<img width="780" alt="Screenshot 2022-05-20 at 12 02 33" src="https://user-images.githubusercontent.com/4037538/169505214-a17d3b08-7243-4d3f-88a5-3d87cb84a5d7.png">

**Comment by Jazzpirate** [comment]
has sparagraph been patched in your context?

**Comment by kohlhase** [comment]
I do not think so, only the patches in `stexthm.sty`.

**Comment by Jazzpirate** [comment]
hmm, ok, can confirm that it's actually usemodule that inserts the spaces -.-

**Comment by Jazzpirate** [comment]
correction: \STEXexport leaked spaces - I thought \ginorespacesandpars wouldn't be necessary anymore, since it's now in ExplSyntax, but apparently tex tokenizes ahead already. Fixed in next push

**Comment by kohlhase** [comment]
great. There is no hurry, good to know that this will be fixed.
