### ISSUE TITLE
cannot give the lang=de to German problems

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#313]
In the Problems, e.g. in `MathHub/MiKoProblems/IWGS/source/regex/mod/regex_morse_code.de.tex`, I currently have 
```
\documentclass{article}
\usepackage[lang=de,solutions,notes,hints,pts,min,noauxreq]{problem}
\libinput{preamble}
```
but this does not load the german babel (presumably, since `stex.sty` takes care of this and the option is not passed on.

**Comment by Jazzpirate** [comment]
This seems to be solved by now?

**Comment by kohlhase** [comment]
No, it is not, `problem.sty` does not take a lang option.

**Comment by Jazzpirate** [comment]
problem.dtx line 86f says `unknown .code:n {\PassOptionsToPackage{\CurrentOption}{stex}}`, and the above file in MiKoProblems seems to work fine...?

**Comment by kohlhase** [comment]
indeed. closing
