### ISSUE TITLE
maxval does not work well with precedences

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#318]
<img width="203" alt="image" src="https://user-images.githubusercontent.com/4037538/172623526-d6e8510a-12cf-483c-a1c0-a57ed0271f41.png">

In `.../MathHub/smglom/arithmetics/source/minmax.en.tex`we have 
```
\symdef{bmaxval}[args=bii,prec=100;\neginfprec x\neginfprec x100,op=\text{max}]{\underset{#2}{\comp{\text{max}}\;} #3}
```
but in `MathHub/MiKoMH/AI/source/rational-decisions/mod/Bellman-equation.en.tex` we have
```
<img width="349" alt="Screenshot 2022-06-08 at 15 01 40" src="https://user-images.githubusercontent.com/4037538/172623005-4a0ab481-886b-470d-a3c1-b80a169eb1e9.png">

see the brackets in the argument below the max.

**Comment by Jazzpirate** [comment]
Quote documentation:

> STEX decides whether to insert parentheses by comparing operator precedences
to a downward precedence pd with initial value \infprec. When encountering a
semantic macro, STEX takes the operator precedence pop of the notation used and
checks whether p_op > p_d. If so, STEX insert parentheses.

Argument precedences are the downwards precedences p_d

**Comment by kohlhase** [comment]
same difference, mit infprec gibt es auch Klammern.

**Comment by Jazzpirate** [comment]
ah. Was ist die operator-precedence von dem \in-symbol an der stelle?
(Übrigens: Ein ternärer \bmaxval dessen erstes argument in der notation nie auftaucht stellt für MMT ein problem dar - im html landet das dann nämlich auch nicht. idealerweise ein \STEXinvisible{#1} mit in die notation packen)

**Comment by kohlhase** [comment]
ich kónnte mir vorstellen, dass das am `\underbrace` liegt.

**Comment by Jazzpirate** [comment]
möglich, aber auch unklar an der stelle - klammern werden eingefügt wenn ein semantische macro auftaucht - also beim \inset (deswegen wird nie geklammert wenn du in nem argument keine semantischen macros benutzt, übrigens). Das \undersetkönnte höchstens ne tex-gruppe aufmachen, das sollte aber an der stelle auch nichts machen, die downwards-precedence wird ja *außerhalb* des \underset gesetzt...

**Comment by kohlhase** [comment]
thanks, confirming it works now for me.
