### ISSUE TITLE
why is stexthm.sty not loaded in notesslides.sty

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#319]
I am currently rethinking the color design for MiKoSlides (and correspondingly for `notesslides.sty`), concretely I do not like that `\titleemph`, `\defemph`, and `\symrefemph` are the same color. At least `\titleemph` should be different; since I like the plain blue for `\titleemph`, I wanted to change `\defemh` and `\symrefemph` to `SteelBlue` (from `[svgnames]xcolor`. 

And there I see that `notesslides.sty` defines 
```
\def\defemph#1{{\textcolor{magenta}{#1}}}
\def\symrefemph#1{{\textcolor{cyan}{#1}}}
\def\compemph#1{{\textcolor{blue}{#1}}}
\def\titleemph#1{{\textcolor{blue}{#1}}}
\def\__omtext_lec#1{(\textcolor{green}{#1})}
```
and `stexthm.sty`defines 
```
\def\compemph#1{\ifcsname textcolor\endcsname\textcolor{blue}{#1}\else#1\fi}
\def\symrefemph#1{\ifcsname textcolor\endcsname\textcolor{blue}{#1}\else#1\fi}
\def\defemph#1{\ifcsname textcolor\endcsname\textcolor{blue}{\textbf{#1}}\else\textbf{#1}\fi}
\def\varemph#1{\ifcsname textcolor\endcsname\textcolor{gray}{#1}\else#1\fi}
```
and that (contrary to what I thought and intended) `notesslides.sty` does not require `stexthm.sty`; instead both are required in `MiKoMH/meta-inf/lib/preamble.sty`. That seems weird and suboptimal, and I would like to chnage this. I suspect that we talked about this, but I forget the intuitions. 

@Jazzpirate could you remind me?

**Comment by Jazzpirate** [comment]
stexthm is pure convenience/examplary for how to style the various macros. I don't think it should be loaded by default anywhere. Similarly, I don't think notesslides should declare any colored highlights - the themes should do that, in my opinion; that's what a theme is for, after all.

i.e. not only should notesslides not load stexthm, I don't think the `\def`s above should be in notesslides either ;)

**Comment by kohlhase** [comment]
> stexthm is pure convenience/examplary for how to style the various macros. I don't think it should be loaded by default anywhere. 

I differ with you there. `stexthm.sty` was developed with and for `notesslides.sty` it is *also* exemplary. I want to use it at least for MiKoMH by default. 

> Similarly, I don't think notesslides should declare any colored highlights - the themes should do that, in my opinion; that's what a theme is for, after all.

I think you are right on this. So I will move the highlights to the sTeX theme.

**Comment by kohlhase** [comment]
OK, I have reworked that and pushed. Things should be cleaner now. 
@Jazzpirate Please have a look and close if you are happy with this.
