### ISSUE TITLE
keeping content from rustex (and ultimately the generated OMDoc)

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#327]
Some stuff I have in (e.g.) the AI notes is only generated there for having suitably self-contained PDF documents. An example are the table of contents in the fragment files. They are useful to have in the PDfs, but should not enter the online course materials. Another example are the syllabi in the `notes/slides-part*.tex` documents. They should not be included either. 
And I am sure there are more situations like these. For this we should have a  mechanism that formats them in `pdflatex`, but not in `RusTeX`. 
@Jazzpirate suggests just setting `\tableofcontents` to `\relax`, but I do not think that is going to be sufficient.

**Comment by Jazzpirate** [comment]
A more interesting example are bibliographies I think. Those we *do* want in the html, but they should only be actually *served* by e.g. MMT iff the current document fragment is not served as part of a larger document, in which case they're probably already captured by a bigger bibliography at the end. So we'd need an equivalent for `\ifinputref` that still processes the content and puts it in the html, but marks it with some class which MMT knows to set to `display:none` if it's not the "top-level document"

**Comment by kohlhase** [comment]
> You mean like `\ifstexhtml`? ;)

Ah, I had forgotten that. Yes, something like that.

**Comment by kohlhase** [comment]
Only that (for the tocs) I now have to do `\ifnotes\ifstexhtml\ifinputref.....` I will probably do something more convenient.

**Comment by Jazzpirate** [comment]
> Only that (for the tocs) I now have to do `\ifnotes\ifstexhtml\ifinputref.....` I will probably do something more convenient.

careful, you probably mean `\ifnotes\ifstexhtml\else\ifinputref...` ;)

**Comment by kohlhase** [comment]
> A more interesting example are bibliographies I think.

indeed. but I think they (together with indices and tocs and such things) are in the category of "generated content". 
* in the pdflatex case, they are generated by tex and statically put into the document. Here the trigger is in the sTeX sources.
* in the html case, I think they should be generated by whatever document management subsystem is used. Here the trigger is in the document manager. 

So conceptually there should not really be a problem for this class.

**Comment by kohlhase** [comment]
> careful, you probably mean `\ifnotes\ifstexhtml\else\ifinputref...` ;)

sure I wanted to say more that I have to care about all three switches.

**Comment by Jazzpirate** [comment]
> But even more interesting is the case of the syllabus. 

I'm not entirely sure I understand the issues regarding the syllabus - isn't that only included in the top-level notes anyway? Are there multiple occurences? (Also: afaik, it's alway input using `\inputref`, right? So ultimately it's not much of an issue if it comes up multiple times, since it's collapsed anyway...)

**Comment by kohlhase** [comment]
In the end I defined two macros `\tociftopnotesnl` and `tociftopnotes` in `preamble.tex` that integrated the three switches.
