### ISSUE TITLE
\sref does not work for sfragment in stex-manual.tex (stex-notesslides.tex)

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#328]
In `doc/packages/stex-notesslides.tex`, we have 
```
    mode and notes mode (see \sref{sec:user:notesslides}).
```
and later 
```
\begin{sfragment}[id=sec:user:notesslides]{Notes and Slides}
```
and the former formats to `(see )`.

**Comment by Jazzpirate** [comment]
...Ok, in that case I can't explain why it *does* work in the places *that* it works in :D

**Comment by Jazzpirate** [comment]
subsumed by a different issue
