### ISSUE TITLE
\begin{problem} without title attribute makes empty ()

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#332]
<img width="189" alt="Screenshot 2022-07-15 at 17 54 44" src="https://user-images.githubusercontent.com/4037538/179260937-a1cf0085-2bfe-4ba8-918b-4d7a7567a510.png">
e.g. in `MathHub/problems/maai-test/source/db/fragments/databases.en.tex`

**Comment by Jazzpirate** [comment]
Is it possible that that is the result of an `\stexpatchproblem` somewhere in the preamble?

**Comment by Jazzpirate** [comment]
fixed; coming with the next commit
