### ISSUE TITLE
another blank leaked in \begin{sproblem}

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#334]
the following screenshot shows it. 
<img width="471" alt="Screenshot 2022-07-18 at 09 32 08" src="https://user-images.githubusercontent.com/4037538/179463809-ec7662b0-43dc-4730-b19b-56dca200fe18.png">

**Comment by kohlhase** [comment]
indeed, it is.

**Comment by kohlhase** [comment]
The leak is back, ... 
<img width="340" alt="Screenshot 2022-07-21 at 06 55 55" src="https://user-images.githubusercontent.com/4037538/180132859-0e52135b-3ee0-4ada-95e5-f72f81fcfdb3.png">

**Comment by Jazzpirate** [comment]
This whitespace does not come from sproblem - it comes from DCMcreators and DCMdate in the preludes. I will push a fix for MiKoCourses/meta-inf

**Comment by kohlhase** [comment]
No, this is still not fixed. Same behavior as above.

**Comment by Jazzpirate** [comment]
did you pull MiKoCourses/meta-inf?

**Comment by kohlhase** [comment]
ah, no. Will try.

**Comment by kohlhase** [comment]
thanks for fixing my stuff.
