### ISSUE TITLE
assertion font mixup. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#337]
The theorem fonts in `beamerthemesTeX.sty` do not work yet. In slides mode we have
<img width="620" alt="Screenshot 2022-07-19 at 09 34 37" src="https://user-images.githubusercontent.com/4037538/179693378-0cf7106b-691d-4309-a68b-901d6ac18d7e.png">

and in notes mode we have 
<img width="387" alt="Screenshot 2022-07-19 at 09 33 34" src="https://user-images.githubusercontent.com/4037538/179693204-63298ead-471b-4770-85e7-9cd051b48c97.png">
the fonts are switched.

**Comment by kohlhase** [comment]
And I do not quite understand why.

**Comment by Jazzpirate** [comment]
This should be "solved" now by having moved away from amsthm?

**Comment by kohlhase** [comment]
Indeed the mixup is resolved (looks identically between slides and notes), but in assertions (e.g. the Theorem) the font should be italic.

**Comment by Jazzpirate** [comment]
ah, indeed, there was a typo in beamerthemesTeX.sty, should be fixed now (pushed) - can you check?

**Comment by kohlhase** [comment]
indeed works.
