### ISSUE TITLE
sref problem in problems

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#339]
Jonas writes: 
![Untitled](https://user-images.githubusercontent.com/4037538/180133117-62a6b459-5d7b-450b-ba2c-b5d1fd2f6db0.png)
Was ist denn aktuell der Befehl für wenn ich in einer Klausuraufgabe auf eine vorherige verweisen möchte?
Früher habe ich dafür \sref{problem-id} verwendet, aber das wird mir hier als "section 4" gerendert, wenn ich lieber "Aufgabe 4.1" hätte.

Denns answers:  scheinbar teild das problem-environment nicht mit, dass das korrekte präfix "Problem" ist

**Comment by kohlhase** [comment]
It would be very nice, if we could have this fixed this (or early next) week for the exams.

**Comment by kohlhase** [comment]
you can test this with `MathHub/MiKoCourses/IWGS/source/SS22/exam.tex`

**Comment by Jazzpirate** [comment]
fixed (push coming soon)

**Comment by kohlhase** [comment]
Indeed this works now.
