### ISSUE TITLE
discrepancy between rustex and pdflatex

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#343]
In `smglom/sets/source/finite-cardinality.en.tex` I get the PDF 
<img width="929" alt="Screenshot 2022-09-02 at 11 35 31" src="https://user-images.githubusercontent.com/4037538/188111009-bfeee350-e340-40e1-b72e-678c87b2f686.png">
and the HTML
<img width="611" alt="Screenshot 2022-09-02 at 11 35 45" src="https://user-images.githubusercontent.com/4037538/188111104-74ff16b1-eedb-4bc0-8efd-8ab5848ad92c.png">
the `#`notation I can understand, I have no idea where the `\theta` comes from.

**Comment by Jazzpirate** [comment]
Uuuh, interesting. That smells like a mistake in the character table for the specific font to me. Will investigate

**Comment by Jazzpirate** [comment]
Fixed in https://github.com/slatex/RusTeX/commit/ba0753f15f2a986a9cdcc34237692a19a0a6026f
(delete .rustex-folder in MathHub after github actions have finished with the commit)
