### ISSUE TITLE
sref problem

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#347]
When I format `MathHub/MiKoMH/AI/source/nlp/fragments/grammar.en.tex`, then the reference 
```
      In the \symname{grammar?grammar} $G$ from \sref[fallback=above]{ex.gsimple}:
```
from `MathHub/MiKoMH/AI/source/nlp/fragments/grammar-sentence-ex.en.tex`, does not work (see page 5 in the pdf).

**Comment by kohlhase** [comment]
Interestingly, the example is also unnumbered, that is probably a leftover from the big item fix a week ago.

**Comment by Jazzpirate** [comment]
found the error, will be fixed with the next sTeX push

**Comment by kohlhase** [comment]
excellent.
