### ISSUE TITLE
rustex should do bibtex

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#354]
It seems that in all the AI notes (and I suspect everywhere else) the references do not work.

**Comment by Jazzpirate** [comment]
I would be very susprised if that had anything to do with rustex. If the .bbl files are there (as generated by pdflatex), rustex should consume them exactly as tex does.

**Comment by Jazzpirate** [comment]
Can you expand on what you mean by "references do not work"? Do they work in pdflatex?

**Comment by kohlhase** [comment]
That's is what I mean. 
<img width="763" alt="Screenshot 2022-09-20 at 15 07 45" src="https://user-images.githubusercontent.com/4037538/191242508-b5958404-5fc2-42f1-8d3d-58c44edce231.png">

and of course they work in pdflatex. Maybe you are not "running rustex twice"?

**Comment by kohlhase** [comment]
oh, and I should add the `[mitchell:...]` is not clickable, ... 

That being said, I am not really sure what I would like to see in the HTML (and reusable-in-multiple documents) case.

**Comment by Jazzpirate** [comment]
No, I'm assuming you ran pdflatex first, so that the .bbl files are there ;)

There's another technicality though: If you're talking about the AI notes - they barely contain content (in the html), since it's all \inputrefs. So the missing reference isn't actually in notes.tex (or notes.bbl), but in the specific fragment that is input as HTML. I think that might be the actual issue:
- File snippet.tex has a \cite{foo}, but in snippet.tex, no bib file is loaded - i.e. the reference is also broken in snippet.pdf.
- File notes.tex does \inputref{snippet} and actually loads the bib file, so the reference properly works in notes.pdf
- But in HTML, notes.html just references snippet.html, and that has the same broken reference as snippet.pdf

does that make sense?

**Comment by kohlhase** [comment]
> No, I'm assuming you ran pdflatex first, so that the .bbl files are there ;)

I am running nothing, ... I got this from Abhishek's new AI notes, so *you* generated that (and maybe forgot pdflatex).

**Comment by Jazzpirate** [comment]
can you tell me where precisely the snippet occurs in the notes?

(Note: the build server, which feeds stexmmt.mathhub.info with content), does 1. pdflatex 2. bibtex/biber 3. pdflatex 4. pdflatex 5. rustex 6. cleanup. So it perfectly reuses the generated files from pdflatex...

**Comment by kohlhase** [comment]
the snippet is in `/MathHub/MiKoMH/AI/source/logic/mod/SAT-phase-transitions.en.tex` and that has a `\libinput{postamble}` at the end. 
So your explanation does not work.

**Comment by Jazzpirate** [comment]
Aha. Other question: Where are the bib files? ;)

**Comment by Jazzpirate** [comment]
I think the main issue is that you're using the kwarc bib repository which I haven't put anywhere on stexmmt.mathhub.info, so a lot of references (or maybe even all of them) should be broken. I can easily put them there, but this reveals a deeper issue, namely that gl.mathhub.info isn't really self-contained

**Comment by kohlhase** [comment]
Ah, that makes more sense. We should think about this carefully. We might fork the directory on gl.mathhub.info and keep it updated.

**Comment by Jazzpirate** [comment]
Indeed, the reference is also broken in the pdf on cortana.

In the future, the promised ideal sTeX DevOps Server should probably have a fork of the bib repo and have it be similarly extensible by others (has no one built a global bibtex library yet? :D )

**Comment by kohlhase** [comment]
yes please.

**Comment by kohlhase** [comment]
But what do we do before this paradise occurs?

**Comment by Jazzpirate** [comment]
probably just clone the repo on cortana and add it to BIBINPUTS...?

**Comment by kohlhase** [comment]
yes, that would be good. Note that `MathHub/MiKoMH/lib/preamble.tex` already has 
```
\usepackage[hyperref=auto,style=alphabetic,backend=bibtex]{biblatex}
\addbibresource{kwarcpubs}
\addbibresource{extpubs}
\addbibresource{kwarccrossrefs}
\addbibresource{extcrossrefs}
```
That  is something we can build on. We could just add the bibs into `MathHub/meta/inf/lib/` via git subrepo.

**Comment by Jazzpirate** [comment]
that would be an alternative approach, and guarantee that MiKoMH is actually self-contained. One would just have to replace \æddbibresource by... what was it? \libaddbibresource? (Will need to check the sTeX sources again)

**Comment by kohlhase** [comment]
I like things to be self-contained, so let's pursue this. But I think that `\libaddresource` might not exist at the moment, and all the `\lib*` do not take `MathHub/meta/inf` into account (see #303)

**Comment by kohlhase** [comment]
should I just add the bibs into `MathHub/meta/inf/lib`?

**Comment by Jazzpirate** [comment]
> I like things to be self-contained, so let's pursue this. But I think that `\libaddresource` might not exist at the moment, and all the `\lib*` do not take `MathHub/meta/inf` into account (see #303)

true, I'm also not a fan of "MathHub/Meta/inf" for the reasons outlined in #303 - but MiKoMH/meta-inf would work fine (and that's where all the citations are anyway)

**Comment by kohlhase** [comment]
there are a couple in smglom (Rudin:73 and so on)  and some in mikoproblems. That's I wanted to get one level up.

**Comment by Jazzpirate** [comment]
Quote the documentation:
```
\stexcode"\addmhbibresource[Some/Archive]{some/file}" searches for a file like
      \stexcode"\mhinput" does, but calls |\addbibresource| to the result and looks for
      the file in the archive root directory directly, rather than the |source|
      directory. Typical invocations are
```
This unfortunately means that `meta-inf` is not considered in as far as it is (not) a math archive. But it means that we can have a dedicated "bibliographies" archive, or just put them in e.g. sTeX/meta-inf (which is a math archive) and in a dedicated `bibs` directory there

**Comment by Jazzpirate** [comment]
...I'd probably prefer the approach of a dedicated bibs math-archive... (as to not explode sTeX/meta-inf, since it contains the omdoc for the metatheory and those kinds of things. Probably a good idea to keep that one small-ish, since the IDE downloads it alongside MMT/urtheories when started for the first time)

**Comment by kohlhase** [comment]
Then we could have a `meta/inf/META-INF/MANIFEST.mf` there, and `meta/inf/source/kbibs/*.bib`via `git subrepo` (and maybe other general bibs over time.

**Comment by kohlhase** [comment]
or (alternatively)  `meta/inf/kbibs` as a Math archive. I think I like this better.

**Comment by kohlhase** [comment]
and mention this in all the `dependencies` in the top-level `MANIFEST.MF`

**Comment by Jazzpirate** [comment]
Might as well call it kwarcbibs then - I'm not sure it makes sense to be short there, but that would work (except that gitlab will probably not allow for it, since `meta/inf` already exists as a repository rather than a group)

**Comment by kohlhase** [comment]
Ah, of course, then `MathHub/meta/kwarcbibs` I guess

**Comment by kohlhase** [comment]
done. I will now make the dependencies at least the one in MiKoMH

**Comment by Jazzpirate** [comment]
Then you can replace the \addbibresources in prelude by `\addmhbibresource[meta/kwarcbibs]{source/kwarc.bib}` and everything should work fine

**Comment by kohlhase** [comment]
I have added the dependency for `MiKoMH/meta-inf/META-INF/MANIFEST.MF`
And I have adapted the `MiKoMH/meta-inf/lib/preamble.tex`accordingly
Now you can do your magic on the server.

**Comment by Jazzpirate** [comment]
note that this will require restarting the buildserver, and then probably lots of fixing content errors ;)

**Comment by kohlhase** [comment]
I am aware. That is not a problem, we will probably do that before October 20. when I need the AI notes to look good :-)
