### ISSUE TITLE
weird error message

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#358]
I get the following error message: 
```

./linear-map.en.tex:16: Package stex Error: No field \bool_set_false:N  in instance V found!
(stex)                
```
on `smglom/linear-algebra/source/mod/linear-mapen.tex` and I have the feeling that instead of ` \bool_set_false:N` there should be a field name.

**Comment by kohlhase** [comment]
funnily enough sometimes it seems to work: 
```
./linear-map.en.tex:16: Package stex Error: No field smul in instance V found!
(stex)                

TYpe <return> to continue.

```

**Comment by Jazzpirate** [comment]
`No field \bool_set_false:N  in instance V found!` is a pretty good indicator that there is something *syntactically* wrong in what you wrote - semantic macros with wrong numbers of arguments etc. This can easily happen if you do not brace arguments correctly, but it's *really really difficult* to detect that that is the case or throw helpful error messages.

In this case, note that in lines 16 and 17, we have `\defeq\V{\mathstruct{...`. `\defeq` takes two arguments, which are therefore `\V`and `\mathstruct{...`. But `\V` itself expects an argument (namely a field name, so what you *wanted* to write was `\V!`, which now needs to be braced as well.

You get the same kinf of error when you do things like `\inset x\V{base-set}`, for example - suddenly the `\V` is taken as second argument for `\inset` and havoc ensues when `\V` itself tries to gobble *its* argument ;)

**Comment by kohlhase** [comment]
Indeed, I wanted to use `\defeq{\V!}` but did not see that. Thanks.
