### ISSUE TITLE
Remove URI from tooltips ('fragment' URLs)

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX#359]
A user can access these by clicking the element.
Optionally, in case no info other than URI is available, we can have something like so:
 "Concept state in module [link]Turing Machine" for  URI ""http://...?turing-machine?state"

**Comment by abchugh** [comment]
Also, remove the `TeX Macro` line.

**Comment by abchugh** [comment]
Also, consider removing the `Type` line especially when its `Type None`. See Percentage hover here:
https://stex-active-doc.kwarc.info/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fmod%2Fgrading.en.xhtml

**Comment by kohlhase** [comment]
Let me re-conceptualize this. The Hover should only give you the "student information" (definition and shortcut to a guided tour; maybe more in the future); for the developer information (type, URI, ...) we should have the onclick panel. There I would have the definition on the left and a "menu" on the right that gives you access to all of these things (I also expect this to grow in the future).

**Comment by Jazzpirate** [comment]
The most interesting aspect to solve here is "What to put in the hover when there is no document fragment associated with a symbol".
The URI gave us something "informative" to put there, but in the ugliest way imaginable, but we should decide on a "default" - the URI can help with disambiguating between concepts with the same name. Consider the number of symbols with name "state" in the MiKoMHsphere - if even one of them does not have a definition, the URI still helps with distinguishing between e.g. "state" in a search problem or the "state" of a turing machine.

I will quickly hack something that says something along the lines of "Symbol `state` in Module `TuringMachine`" (ideally with links) if no definition exists, but I'm sure in the long run we can think of something better

**Comment by kohlhase** [comment]
I support this idea.

**Comment by Jazzpirate** [comment]
Done
