### ISSUE TITLE
Some hover links seem to be broken

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX#362]
Example:
When percentage sign is used [here](https://stex-active-doc.kwarc.info/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fmod%2Fgrading.en.xhtml), the notations are shown when we click on the concept but the definition is missing.

https://gl.mathhub.info/smglom/arithmetics/-/blob/main/source/mod/percentage.en.tex

**Comment by abchugh** [comment]
Also, see hover on `Rational Number` in https://stex-active-doc.kwarc.info/browser/%3AsTeX%2Fdocument%3Farchive%3Dsmglom%2Farithmetics%26filepath%3Dpercentage.en.xhtml

**Comment by kohlhase** [comment]
> Example: When percentage sign is used [here](https://stex-active-doc.kwarc.info/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fmod%2Fgrading.en.xhtml), the notations are shown when we click on the concept but the definition is missing.
> 
> https://gl.mathhub.info/smglom/arithmetics/-/blob/main/source/mod/percentage.en.tex

This is something we should really investigate, because there is a definition in the sTeX source, I have seen the "missing definition" in quite a few other places, and it is annoying.

**Comment by Jazzpirate** [comment]
> This is something we should really investigate, because there is a definition in the sTeX source, I have seen the "missing definition" in quite a few other places, and it is annoying.

The information is missing in the sources: 1. \begin{sdefinition} has no `for=` attribute and 2. The definition does not contain any \definame or \definiens. This means sTeX/MMT have no way of determining what this is a definition *for*.

**Comment by kohlhase** [comment]
Ah, very interesting. Then we should have the linter predict them (see https://github.com/slatex/sTeX-IDE/issues/19).
