### ISSUE TITLE
I cannot see the cause of this error

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#373]
I have stared at this for a while and cannot see the problemf in `MiKoMH/AI/source/probabilistic-reasoning/slides/probdist.en.tex`. 
I get errors
```
./probdist.en.tex:63: Illegal parameter number in definition of \iterate.
<to be read again> 
                   1
l.63 \end{frame}
                
./probdist.en.tex:63: Illegal parameter number in definition of \iterate.
<to be read again> 
                   1
l.63 \end{frame}
                
./probdist.en.tex:63: Illegal parameter number in definition of \beamer@doifinframe.
<to be read again> 
                   1
l.63 \end{frame}
```
which goes away when I comment out line 38: 
```
      \varseq{Xseq}1n{\comp{X}_{#1}}
```
But I cannot understand why.

**Comment by kohlhase** [comment]
and this messes up a lot of things, since it is a widely used import

**Comment by Jazzpirate** [comment]
Solved by adding `[fragile]` to `\begin{frame}`

**Comment by kohlhase** [comment]
For the Record: Actually, there was another problem: `\ProbDist` should have had `[args=a` but had `[args=1` so it was not fit to be applied to a sequence.
