### ISSUE TITLE
sdefinition/sassertion/... counter does not reset with section

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#377]
In the AI notes, the statement counter does not seem to reset with the section (under pdflatex). See 

<img width="790" alt="Screenshot 2022-11-06 at 17 09 29" src="https://user-images.githubusercontent.com/4037538/200181638-ffca0ae1-0d2f-4edb-bbe8-cb55c82b0bc3.png">

**Comment by Jazzpirate** [comment]
should be fixed now, can you check?

**Comment by kohlhase** [comment]
Indeed works now. Thanks
