### ISSUE TITLE
presentation improvements for mcb and scb

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#395]
currently, `{mcb}` and `{scb}` could use a bit more love in the presentation. In the moment, 
```
  \begin{subproblem}
    There is a walk from $a$ to $b$ that visits each \sr{node}{vertex} of $G$ ...
    \begin{subproblem}
      ...at most once.
      \begin{scb}[style=inline]
        \scc[T]{\sn{constant}}
        \scc{\sn{linear}, i.e. $\atmost{\natplus{\card\nodes,\card\edges}}$}
        \scc{\sn{polynomial}}
        \scc{\sn{exponential}}
      \end{scb}
    \end{subproblem}
```
(from `MathHub/problems/maai-test/source/logic/prob/graph-complexities-lutz.en.tex` gives 
<img width="539" alt="Screenshot 2023-08-04 at 14 45 36" src="https://github.com/slatex/sTeX/assets/4037538/8dab2e93-90cf-48b4-b570-792e87059833">
with 
<img width="494" alt="Screenshot 2023-08-04 at 14 47 25" src="https://github.com/slatex/sTeX/assets/4037538/e01d450c-d42d-4d9e-8592-1302e38ec524">
below. 

There are a couple of problems: 
- [x] there is no space after the circle (even though there is a `~` in the `\scc` macro; weird. 
- [ ] The footnotes for the result are wasteful, we should just juse `\circledcirc` from `amssymb.sty` for the `[T]` case of `\scc`  and only have the footnotes if there is feedback via `Ttext` for `Ftext`. For  the `[T]` case of `\mcc` we could use something like `\makebox[0pt][l]{$\square$}\raisebox{.15ex}{\hspace{0.1em}$\checkmark$}`

**Comment by Jazzpirate** [comment]
done
