### ISSUE TITLE
slashes in \symdecl/\symref do not work

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#418]
In `MiKoMH/AI/source/planning/slides/and-or-search.en.tex` we have 
```
\symdecl*{AND/OR tree}
...
\begin{sparagraph}[title=Idea]
   Use \sns{AND/OR tree} as \sns{data structure} for
```
but the result is 
<img width="240" alt="Screenshot 2024-02-04 at 16 45 43" src="https://github.com/slatex/sTeX/assets/4037538/d06344fb-27a6-4a48-95e9-e8c3b834cfd5">

**Comment by kohlhase** [comment]
It would be great to have a fix for this soon, so that I can use that in the coming tuesday quiz.

**Comment by Jazzpirate** [comment]
`/` is a reserved separator between namespace/URI segments. This is not fixable any time soon

**Comment by Jazzpirate** [comment]
(There have to be some restrictions on what is allowed in a name, seeing as they are parts of URI's, and we want \symname et al to accept prefixes for disambiguation)

**Comment by kohlhase** [comment]
OK, thanks. I have changed the symbol name. 
Is this limitation documented?
