### ISSUE TITLE
weird problem with usemodule and {sexample}[for=

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#422]
In `MiKoMH/AI/source/ml/slides/mlc-logistic.en.tex` we have 
```
...
\usemodule{ml/slides?logistic-regression}
...
\begin{sexample}[...,for=logistic regression]
```
and it formats without problems. 
But when I format ``MiKoMH/AI/source/ml/slides/logistic-regression.en.tex` which contains
```
\importmodule{ml/slides?mlc-logistic}
\symdecl*{logistic regression}
...
```
(note the `\importmodule/\usemodule` cycle) I get the error message: 
```
(/Users/kohlhase/localmh/MathHub/MiKoMH/AI/source/ml/slides/mlc-logistic.en.tex! Package stex Error: No symbol logistic regression found!

Type <return> to continue.
 ...                                              
                                                  
l.47 ...s in Weight Space,for=logistic regression]
```
I do not thinkl this should be the case.

**Comment by kohlhase** [comment]
This happens a couple of times in the current build queue (e.g. with the `tense` problems).

**Comment by Jazzpirate** [comment]
apparently `sexample` scans the for-list in sms mode. This is necessary for sdefinition et al to figure out which symbols are defined, but for examples the for-list should be ignored in dependencies. Working on it

**Comment by Jazzpirate** [comment]
seems to be fixed for the logistic-regression example. The `tense`-problems on the build server seem to be real problems with missing symbols and unrelated
